title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
just_the_docs:
  # Include this file at the end of <head> in every page
  includes:
    head:
      - head_custom.html


url: https://xinshengqin.github.io
baseurl: ""

